/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ChiTietHoaDonDAO;
import dao.DatabaseHelper;
import dao.DoUongDAO;
import dao.HoaDonDAO;
import dao.KhachHangDAO;
import dao.NhanVienDAO;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ChiTietHoaDon;
import model.DoUong;
import model.HoaDon;
import model.KhachHang;
import model.NhanVien;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class BanHangJPanel extends javax.swing.JPanel {

    List<DoUong> listDoUong = new ArrayList<>();
    DoUongDAO duDAO = new DoUongDAO();

    HoaDon hoaDon = new HoaDon();
    HoaDonDAO hdDAO = new HoaDonDAO();

    ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();

    KhachHangDAO khDAO = new KhachHangDAO();
    KhachHang kh = new KhachHang();

    NhanVienDAO nvDAO = new NhanVienDAO();
    NhanVien nv = new NhanVien();

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    private TableRowSorter<TableModel> rowSorter = null;

    /**
     * Creates new form BanHangJPanel
     */
    public BanHangJPanel(NhanVien nv) {
        initComponents();

        this.nv = nv;

        hoaDon = null;
        kh = null;

        loadDoUongToTableMenu();

        // Tìm kiếm txtSearch
        DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
        rowSorter = new TableRowSorter<>(model);
        tblMenu.setRowSorter(rowSorter);

        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txtSearch.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txtSearch.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaDU = new javax.swing.JTextField();
        txtTenDU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnThemDU = new javax.swing.JButton();
        btnXoaDU = new javax.swing.JButton();
        btnResetHD = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        txtMaHD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNgayHD = new javax.swing.JTextField();
        btnThongTinKH = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        btnLuuHoaDon = new javax.swing.JButton();
        btnXoaHoaDon = new javax.swing.JButton();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLichSuGiaoDich = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BÁN HÀNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("MENU"));

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MÃ ĐỒ UỐNG", "TÊN ĐỒ UỐNG", "ĐƠN GIÁ"
            }
        ));
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        jLabel11.setText("Tìm kiếm:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("ORDER"));

        jLabel3.setText("Mã đồ uống:");

        txtMaDU.setEditable(false);

        txtTenDU.setEditable(false);

        jLabel4.setText("Tên đồ uống:");

        txtDonGia.setEditable(false);

        jLabel5.setText("Đơn giá:");

        jLabel6.setText("Số lượng:");

        btnThemDU.setText("Thêm");
        btnThemDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDUActionPerformed(evt);
            }
        });

        btnXoaDU.setText("Xóa");
        btnXoaDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDUActionPerformed(evt);
            }
        });

        btnResetHD.setText("Reset");
        btnResetHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetHDActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        txtMaHD.setEditable(false);

        jLabel8.setText("Mã hóa đơn:");

        jLabel9.setText("Mã KH:");

        txtMaKH.setEditable(false);

        jLabel2.setText("Mã NV:");

        txtMaNV.setEditable(false);

        jLabel10.setText("Ngày HD:");

        txtNgayHD.setEditable(false);

        btnThongTinKH.setText("Thông tin khách hàng");
        btnThongTinKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaKH)
                                            .addComponent(txtNgayHD)
                                            .addComponent(txtMaNV)))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTenDU, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaDU, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtMaHD))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThemDU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaDU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResetHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThongTinKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDonGia, txtMaDU, txtSoLuong, txtTenDU});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThongTinKH)
                    .addComponent(btnResetHD)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoaDU)
                        .addComponent(btnMoi)
                        .addComponent(btnThemDU)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Thành tiền:");

        txtThanhTien.setEditable(false);
        txtThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnLuuHoaDon.setText("Thanh toán");
        btnLuuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuHoaDonActionPerformed(evt);
            }
        });

        btnXoaHoaDon.setText("Xóa hóa đơn");
        btnXoaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHoaDonActionPerformed(evt);
            }
        });

        txtTienKhachDua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyPressed(evt);
            }
        });

        jLabel12.setText("Tiền khách đưa:");

        jLabel13.setText("Tiền thừa:");

        txtTienThua.setEditable(false);
        txtTienThua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnLuuHoaDon)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaHoaDon)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtThanhTien)
                    .addComponent(txtTienKhachDua)
                    .addComponent(txtTienThua))
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLuuHoaDon, btnXoaHoaDon});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuuHoaDon)
                    .addComponent(btnXoaHoaDon))
                .addContainerGap())
        );

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ ĐỒ UỐNG", "TÊN ĐỒ UỐNG", "ĐƠN GIÁ", "SỐ LƯỢNG"
            }
        ));
        jScrollPane2.setViewportView(tblHoaDon);

        tblLichSuGiaoDich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "Mã NV", "Mã KH", "Ngày HD", "Tổng tiền"
            }
        ));
        tblLichSuGiaoDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLichSuGiaoDichMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLichSuGiaoDich);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane3)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        selectDoUong();
    }//GEN-LAST:event_tblMenuMouseClicked

    private void btnThemDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDUActionPerformed
        addDoUong();
        txtThanhTien.setText(new BigDecimal(totalPrice()) + "");
    }//GEN-LAST:event_btnThemDUActionPerformed

    private void btnXoaDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDUActionPerformed
        removeDoUong();
        txtThanhTien.setText(new BigDecimal(totalPrice()) + "");
    }//GEN-LAST:event_btnXoaDUActionPerformed

    private void btnResetHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetHDActionPerformed

        if (txtMaHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Chưa tạo hóa đơn mới");
        } else if (!tblLichSuGiaoDich.hasFocus() && !txtMaHD.getText().isEmpty()) {
            int id = Integer.parseInt(txtMaHD.getText());

            hoaDon = hdDAO.getHoaDonByID(id);
            hdDAO.delete(hoaDon);

            clear();
            fillToTableHoaDon();
            loadCart();
        } else {
            clear();
            fillToTableHoaDon();
            loadCart();
        }


    }//GEN-LAST:event_btnResetHDActionPerformed

    private void btnLuuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuHoaDonActionPerformed
        saveCart();
        inHoaDon();
    }//GEN-LAST:event_btnLuuHoaDonActionPerformed

    private void btnXoaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHoaDonActionPerformed
        removeCart();
    }//GEN-LAST:event_btnXoaHoaDonActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // import java.sql.Timestamp;
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        Date date = java.util.Calendar.getInstance().getTime();

        hoaDon = new HoaDon();

        hoaDon.setId((int) timestamp.getTime());
        hoaDon.setNhanVien(nv);
        hoaDon.setKhachHang(kh);

        hoaDon.setNgayHD(date);

        hoaDon.setTongTien(0);

        hdDAO.add(hoaDon);

        txtMaHD.setText(hoaDon.getId() + "");

        if (kh == null) {
            txtMaKH.setText("");
        } else {
            txtMaKH.setText(hoaDon.getKhachHang().getMaKH());
        }

        txtMaNV.setText(hoaDon.getNhanVien().getMaNV());
        txtNgayHD.setText(sdf.format(hoaDon.getNgayHD()));
        btnMoi.setEnabled(false);

    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThongTinKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinKHActionPerformed
        KhachHangDialog frame = new KhachHangDialog(null, true);
        frame.setVisible(true);
        kh = frame.khachHang;
        txtMaKH.setText(kh.getMaKH());
    }//GEN-LAST:event_btnThongTinKHActionPerformed

    private void tblLichSuGiaoDichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLichSuGiaoDichMouseClicked
        viewCart();
        selectCart();
    }//GEN-LAST:event_tblLichSuGiaoDichMouseClicked

    public void inHoaDon() {
        if (hoaDon == null) {
            return;
        }

        try {
            Hashtable map = new Hashtable();
            JasperReport rpt = JasperCompileManager.compileReport("src\\report\\rptHoaDon.jrxml");

            Long maHD = Long.valueOf(hoaDon.getId());

            map.put("MaHD", maHD);

            Connection con = DatabaseHelper.getDBConnect();
            JasperPrint print = JasperFillManager.fillReport(rpt, map, con);
            JasperViewer.viewReport(print, false);
        } catch (JRException ex) {
            Logger.getLogger(BanHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void txtTienKhachDuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyPressed
        int tongTien = Integer.parseInt(txtThanhTien.getText());

        int tienKhachDua = 0;

        try {
            tienKhachDua = Integer.parseInt(txtTienKhachDua.getText());
        } catch (Exception e) {
            return;
        }

        if (tienKhachDua >= tongTien) {
            int tienThua = tienKhachDua - tongTien;

            txtTienThua.setText(tienThua + "");
        }


    }//GEN-LAST:event_txtTienKhachDuaKeyPressed

    public void loadDoUongToTableMenu() {
        listDoUong = duDAO.getAll();

        DefaultTableModel tblModel = (DefaultTableModel) tblMenu.getModel();
        tblModel.setRowCount(0);
        
        

        for (DoUong du : listDoUong) {
            if (du.isTrangThai()) {
                Object row[] = {du.getMaDU(), du.getTenDU(), du.getGiaDU()};
                tblModel.addRow(row);
            }
        }
    }

    public void selectDoUong() {
        int index = tblMenu.getSelectedRow();
        int maDU = (int) tblMenu.getValueAt(index, 0);
        DoUong du = duDAO.getDoUongByID(maDU);
        txtMaDU.setText(du.getMaDU() + "");
        txtTenDU.setText(du.getTenDU());
        txtSoLuong.setText("1");
        txtDonGia.setText(new BigDecimal(du.getGiaDU()) + "");
    }

    private void addDoUong() {
        int index = tblMenu.getSelectedRow();

        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đồ uống");
            return;
        }

        int maDU = (int) tblMenu.getValueAt(index, 0);
        DoUong du = duDAO.getDoUongByID(maDU);

        if (hoaDon == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa tạo hóa đơn mới");
            return;
        }

        //DoUong du = listDoUong.get(index);
        int soLuong;

        try {
            soLuong = Integer.parseInt(txtSoLuong.getText());
            if (soLuong < 1) {
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số > 0");
            return;
        }

        ChiTietHoaDon cthd = new ChiTietHoaDon(du, hoaDon, soLuong, "");
        boolean check = false;

        //int maDU = du.getMaDU();
        for (ChiTietHoaDon item : cthdDAO.getCTHDByMaHD((int) hoaDon.getId())) {
            if (item.getDoUong().getMaDU() == maDU) {
                soLuong = soLuong + item.getSoLuong();
                cthd.setSoLuong(soLuong);
                cthdDAO.update(cthd);
                check = true;
                break;
            }
        }

        if (check == false) {
            cthdDAO.add(cthd);
        }

        fillToTableHoaDon();
    }

    private double totalPrice() {
        double total = 0d;

        if (hoaDon == null) {
            return 0;
        }

        for (ChiTietHoaDon item : cthdDAO.getCTHDByMaHD((int) hoaDon.getId())) {
            DoUong du = item.getDoUong();
            int soLuong = item.getSoLuong();
            total += du.getGiaDU() * soLuong;
        }

        return total;
    }

    private void removeDoUong() {
        try {
            int index = tblHoaDon.getSelectedRow();
            String maDU = tblHoaDon.getValueAt(index, 0).toString();

            for (ChiTietHoaDon item : cthdDAO.getCTHDByMaHD((int) hoaDon.getId())) {
                if (item.getDoUong().getMaDU() == Integer.parseInt(maDU)) {
                    cthdDAO.delete(item);
                    break;
                }
            }

            fillToTableHoaDon();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đồ uống để xóa");
        }
    }

    private void clear() {
        hoaDon = new HoaDon();
        hoaDon = null;
        kh = null;

        btnMoi.setEnabled(true);

        tblMenu.clearSelection();
        tblHoaDon.clearSelection();
        tblLichSuGiaoDich.clearSelection();

        txtMaDU.setText("");
        txtTenDU.setText("");
        txtDonGia.setText("");
        txtSoLuong.setText("");
        txtThanhTien.setText("");
        txtMaHD.setText("");
        txtMaKH.setText("");
        txtMaNV.setText("");
        txtNgayHD.setText("");
        txtSearch.setText("");
        txtTienKhachDua.setText("");
        txtTienThua.setText("");

        btnMoi.setEnabled(true);
    }

    private void fillToTableHoaDon() {
        DefaultTableModel tblModel = (DefaultTableModel) tblHoaDon.getModel();
        tblModel.setRowCount(0);

        if (hoaDon == null) {
            tblModel.setRowCount(0);
            return;
        }

        for (ChiTietHoaDon item : cthdDAO.getCTHDByMaHD((int) hoaDon.getId())) {
            DoUong du = item.getDoUong();
            int soLuong = item.getSoLuong();
            Object row[] = {du.getMaDU(), du.getTenDU(), new BigDecimal(du.getGiaDU()), soLuong};
            tblModel.addRow(row);

        }
    }

    public void saveCart() {
        if (hoaDon == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn hóa đơn");
            return;
        }

        if (cthdDAO.getCTHDByMaHD(hoaDon.getId()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hóa đơn rỗng");
            return;
        }

        if (hoaDon.getKhachHang() != null) {
            hoaDon.setKhachHang(hoaDon.getKhachHang());
        } else {
            hoaDon.setKhachHang(kh);
        }

        hoaDon.setTongTien((int) totalPrice());

        if (txtTienKhachDua.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số tiền khách đưa");
            return;
        }

        try {
            hoaDon.setTienKhachDua(Integer.parseInt(txtTienKhachDua.getText()));
            hoaDon.setTienThua(Integer.parseInt(txtTienThua.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số tiền khách đưa");
            return;
        }

        hdDAO.update(hoaDon);

        loadCart();

        //clear();

        fillToTableHoaDon();

        txtThanhTien.setText(new BigDecimal(totalPrice()) + "");

    }

    public void loadCart() {
        DefaultTableModel tblModel = (DefaultTableModel) tblLichSuGiaoDich.getModel();
        tblModel.setRowCount(0);

        if (hoaDon == null) {
            tblModel.setRowCount(0);
            return;
        }

        String maKH = null;
        if (hoaDon.getKhachHang() != null) {
            maKH = hoaDon.getKhachHang().getMaKH();
        }

        Object row[] = {
            hoaDon.getId(),
            hoaDon.getNhanVien().getMaNV(),
            maKH,
            sdf.format(hoaDon.getNgayHD()),
            hoaDon.getTongTien()
        };
        tblModel.addRow(row);

    }

    public void viewCart() {
        String idCart = String.valueOf(tblLichSuGiaoDich.getValueAt(tblLichSuGiaoDich.getSelectedRow(), 0));
        int id = Integer.parseInt(idCart);

        hoaDon = hdDAO.getHoaDonByID(id);

        fillToTableHoaDon();

        txtThanhTien.setText(new BigDecimal(totalPrice()) + "");
    }

    public void selectCart() {
        txtMaHD.setText(hoaDon.getId() + "");

        String maKH = null;
        if (hoaDon.getKhachHang() != null) {
            maKH = hoaDon.getKhachHang().getMaKH();
        }
        txtMaKH.setText(maKH);

        txtMaNV.setText(hoaDon.getNhanVien().getMaNV());
        txtNgayHD.setText(sdf.format(hoaDon.getNgayHD()));
        txtTienKhachDua.setText(hoaDon.getTienKhachDua() + "");
        txtTienThua.setText(hoaDon.getTienThua() + "");
    }

    public void removeCart() {

        if (txtMaHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Chưa tạo hóa đơn mới");
        } else {
            int id = Integer.parseInt(txtMaHD.getText());
            hoaDon = hdDAO.getHoaDonByID(id);
            hdDAO.delete(hoaDon);

            clear();
            fillToTableHoaDon();
            loadCart();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuHoaDon;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnResetHD;
    private javax.swing.JButton btnThemDU;
    private javax.swing.JButton btnThongTinKH;
    private javax.swing.JButton btnXoaDU;
    private javax.swing.JButton btnXoaHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblLichSuGiaoDich;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaDU;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayHD;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenDU;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienThua;
    // End of variables declaration//GEN-END:variables
}
